CREATE DATABASE IF NOT EXISTS `ac2049`;
USE ac2049;


CREATE TABLE IF NOT EXISTS `tbidentify`(
`identify_id` BIGINT UNSIGNED AUTO_INCREMENT,
`appid` CHAR(32) NOT NULL,
`groupid` VARCHAR(64) NULL,
`personid` VARCHAR(64) NOT NULL,
`faceid` VARCHAR(64) NOT NULL DEFAULT "noid",
`updatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`feature` BLOB NOT NULL,
PRIMARY KEY(`identify_id`),
KEY (`appid`),
KEY (`personid`),
KEY (`updatetime`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;